"""Tests for the γ-calibration scaffolding.

Three things to verify:

1. The closed-form intercept fit recovers the true ``c`` from synthetic
   B-factors generated by the same model (round-trip test).
2. Per-protein CV is low when the synthetic data uses a single
   underlying ``c`` (sanity of CV as a calibration-quality metric).
3. The stiffness probe correctly classifies a uniform-γ bridge as
   well-behaved and a wildly-varying bridge as fragile.
4. The bfactor dataset filter and stratified split work as advertised.
"""

import numpy as np
import pytest

from tope.data.bfactor import (
    BFactorDataset,
    BFactorFilter,
    BFactorRecord,
    build_dataset,
    stratified_split,
)
from tope.dynamics.calibration import (
    B_PREFACTOR,
    KB_KCAL,
    compute_spectrum,
    fit_gamma_calibration,
    held_out_drift,
    make_uniform_stiffness_fn,
    probe_stiffness_distribution,
    uniform_stiffness,
)


def _random_globular_coords(n: int, seed: int = 0) -> np.ndarray:
    """Cα coords clustered in 3D — non-collinear, generic ANM geometry."""
    rng = np.random.default_rng(seed)
    return rng.normal(scale=4.0, size=(n, 3))


def _synthetic_record(
    n: int,
    c_true: float,
    seed: int = 0,
    cutoff: float = 12.0,
    T_K: float = 298.15,
) -> BFactorRecord:
    """Generate B-factors consistent with a known ``c_true`` and uniform γ=1.

    Inverts the calibration formula: pick coords, build the c=1 Hessian,
    compute S_i = Σ_m |v_m,i|²/λ̃_m, and set
    ``B_exp_i = (8π²/3) · (k_B T / c_true) · S_i``. Calibrating against
    this should recover ``c_true`` to numerical precision.
    """
    coords = _random_globular_coords(n, seed=seed)
    record = BFactorRecord(
        pdb_id=f"syn{seed}",
        chain_id="A",
        n_residues=n,
        coords=coords,
        b_factors=np.ones(n),  # placeholder, overwritten below
        residue_names=["ALA"] * n,
        residue_numbers=list(range(100, 100 + n)),
        resolution_A=1.5,
        method="X-RAY DIFFRACTION",
    )
    spec = compute_spectrum(record, make_uniform_stiffness_fn(1.0),
                            cutoff_A=cutoff)
    S = np.exp(spec.log_S)
    b_exp = B_PREFACTOR * (KB_KCAL * T_K / c_true) * S
    record.b_factors = b_exp
    return record


# ── BFactorRecord and filters ────────────────────────────────────────────────

def test_size_buckets():
    rec_small = BFactorRecord("a", "A", 80, np.zeros((80, 3)), np.ones(80))
    rec_med = BFactorRecord("b", "A", 180, np.zeros((180, 3)), np.ones(180))
    rec_large = BFactorRecord("c", "A", 400, np.zeros((400, 3)), np.ones(400))
    assert rec_small.size_bucket() == "small"
    assert rec_med.size_bucket() == "medium"
    assert rec_large.size_bucket() == "large"


def test_bfactor_filter_rejects_low_resolution():
    filt = BFactorFilter(max_resolution_A=2.5)
    ok, _ = filt.accept_structure(3.0, "X-RAY DIFFRACTION", 100)
    assert not ok
    ok, _ = filt.accept_structure(2.0, "X-RAY DIFFRACTION", 100)
    assert ok


def test_bfactor_filter_rejects_wrong_method():
    filt = BFactorFilter(allowed_methods=("X-RAY DIFFRACTION",))
    ok, _ = filt.accept_structure(2.0, "NMR", 100)
    assert not ok


def test_bfactor_filter_size_bounds():
    filt = BFactorFilter(min_residues=50, max_residues=400)
    assert not filt.accept_structure(2.0, "X-RAY DIFFRACTION", 30)[0]
    assert not filt.accept_structure(2.0, "X-RAY DIFFRACTION", 500)[0]
    assert filt.accept_structure(2.0, "X-RAY DIFFRACTION", 100)[0]


# ── Stratified split ─────────────────────────────────────────────────────────

def test_stratified_split_preserves_size_mix():
    records = (
        [BFactorRecord(f"s{i}", "A", 80, np.zeros((80, 3)), np.ones(80))
         for i in range(10)]
        + [BFactorRecord(f"m{i}", "A", 180, np.zeros((180, 3)), np.ones(180))
           for i in range(10)]
        + [BFactorRecord(f"l{i}", "A", 400, np.zeros((400, 3)), np.ones(400))
           for i in range(10)]
    )
    cal, val = stratified_split(records, calibration_fraction=0.6, seed=42)
    n_small_cal = sum(1 for pid in cal if pid.startswith("s"))
    n_small_val = sum(1 for pid in val if pid.startswith("s"))
    # 6/4 split per bucket of 10 (rounded).
    assert n_small_cal == 6
    assert n_small_val == 4


def test_build_dataset_records_calibration_membership():
    records = [
        BFactorRecord(f"p{i}", "A", 100, np.zeros((100, 3)), np.ones(100))
        for i in range(8)
    ]
    ds = build_dataset(records, calibration_fraction=0.5, seed=0)
    assert len(ds.calibration_ids) + len(ds.validation_ids) == 8
    assert set(ds.calibration_ids).isdisjoint(set(ds.validation_ids))


# ── Calibration round-trip ───────────────────────────────────────────────────

def test_calibration_recovers_known_c_uniform_stiffness():
    """The acid test: generate synthetic B-factors from a known c
    using uniform-γ ANM, then fit. Should recover c to high precision."""
    c_true = 2.7
    records = [_synthetic_record(n=12, c_true=c_true, seed=i) for i in range(4)]
    result = fit_gamma_calibration(
        records, make_uniform_stiffness_fn(1.0), T_K=298.15,
        compute_baseline=False,
    )
    np.testing.assert_allclose(result.c, c_true, rtol=1e-6)


def test_calibration_cv_is_small_when_data_is_consistent():
    """If all synthetic proteins share one true c, per-protein CV ≈ 0."""
    c_true = 4.1
    records = [_synthetic_record(n=14, c_true=c_true, seed=i) for i in range(6)]
    result = fit_gamma_calibration(
        records, make_uniform_stiffness_fn(1.0),
        compute_baseline=False,
    )
    assert result.cv < 1e-9


def test_calibration_cv_grows_when_proteins_disagree():
    """Mix proteins drawn from different true c values ⇒ CV jumps."""
    records = (
        [_synthetic_record(n=12, c_true=2.0, seed=i) for i in range(3)]
        + [_synthetic_record(n=12, c_true=8.0, seed=10 + i) for i in range(3)]
    )
    result = fit_gamma_calibration(
        records, make_uniform_stiffness_fn(1.0),
        compute_baseline=False,
    )
    assert result.cv > 0.3


def test_calibration_pearson_r_is_one_on_synthetic_match():
    """When the model matches the data, log-space r should be ≈ 1."""
    records = [_synthetic_record(n=16, c_true=3.3, seed=i) for i in range(5)]
    result = fit_gamma_calibration(
        records, make_uniform_stiffness_fn(1.0),
        compute_baseline=False,
    )
    assert result.pearson_r_log > 0.999


def test_calibration_passes_spec_on_synthetic():
    """Acceptance criteria: CV < 20%, r > 0.3, beats baseline (≥)."""
    records = [_synthetic_record(n=14, c_true=2.5, seed=i) for i in range(5)]
    result = fit_gamma_calibration(records, make_uniform_stiffness_fn(1.0))
    ok, reason = result.passes_spec()
    assert ok, reason


def test_held_out_drift_reports_consistent_c_on_synthetic():
    """Calibration on disjoint splits drawn from the same model should
    give c-values within drift tolerance (well below 10%)."""
    records = [_synthetic_record(n=14, c_true=3.6, seed=i) for i in range(10)]
    cal = records[:5]
    val = records[5:]
    res = held_out_drift(cal, val, make_uniform_stiffness_fn(1.0))
    assert res.drift_fraction < 0.05


# ── Stiffness probe ──────────────────────────────────────────────────────────

def test_probe_uniform_bridge_is_flat():
    records = [_synthetic_record(n=12, c_true=1.0, seed=i) for i in range(3)]
    probe = probe_stiffness_distribution(records, make_uniform_stiffness_fn(1.0))
    assert probe.log10_range < 1e-9
    assert probe.n_contacts > 0


def test_probe_wildly_varying_bridge_flags_fragile():
    """A bridge that returns wildly varying per-contact stiffness should
    register a large log10 spread — the calibration-fragility signal."""
    records = [_synthetic_record(n=10, c_true=1.0, seed=i) for i in range(3)]

    def variable_stiffness(coords, pairs):
        # Stiffness scales as distance² — spans orders of magnitude
        # across a typical ANM contact graph.
        out = {}
        for i, j in pairs:
            d2 = float(np.sum((coords[j] - coords[i]) ** 2))
            out[(int(i), int(j))] = d2 ** 2
        return out

    probe = probe_stiffness_distribution(records, variable_stiffness)
    assert probe.log10_range > 1.0   # >1 order of magnitude ⇒ flagged


# ── End-to-end: bridge-agnostic, isotropic vs tensor stiffness ───────────────

def test_calibration_accepts_tensor_stiffness_bridge():
    """The calibration must handle a bridge returning 3×3 SPD blocks
    (the tensor-ANM path).

    Note: scalar-ANM and identity-tensor-ANM are *different* models
    (rank-1 vs rank-3 stiffness per contact). We can't use synthetic
    B-factors generated under one to test calibration of the other;
    this test only checks end-to-end runnability and per-protein
    consistency on a *matched* (data, model) pair.
    """
    def tensor_uniform(coords, pairs):
        return {(int(i), int(j)): np.eye(3) for i, j in pairs}

    # Generate synthetic B-factors using the tensor-ANM model itself.
    def make_tensor_record(n, c_true, seed):
        coords = _random_globular_coords(n, seed=seed)
        rec = BFactorRecord(
            pdb_id=f"tens{seed}", chain_id="A", n_residues=n,
            coords=coords, b_factors=np.ones(n),
            residue_names=["ALA"] * n,
            residue_numbers=list(range(100, 100 + n)),
            resolution_A=1.5, method="X-RAY DIFFRACTION",
        )
        spec = compute_spectrum(rec, tensor_uniform, cutoff_A=12.0)
        S = np.exp(spec.log_S)
        rec.b_factors = B_PREFACTOR * (KB_KCAL * 298.15 / c_true) * S
        return rec

    c_true = 1.5
    records = [make_tensor_record(10, c_true, i) for i in range(3)]
    result = fit_gamma_calibration(records, tensor_uniform,
                                   compute_baseline=False)
    # With matched model+data, calibration recovers c_true exactly.
    np.testing.assert_allclose(result.c, c_true, rtol=1e-6)
    assert result.cv < 1e-9
